### ISSUE TITLE
Set max width for text to improve readability

### ISSUE THREAD

**Issue by k-nut** [jsunconf/2018.jsunconf.eu#13]
I propose limiting the text width to something like 60 characters which makes the text much more readable especially on big screens. 

I also changed the text adjustment to `justified` for even better readability although this can be argued about. 

How do you like this change?

All that is needed is actually the following (slightly hacky) four lines of css:

```
p {
    padding: 0 calc(calc(100% - 60ch)/2);
    text-align: justify;
}
```

Before
![](https://screenshotscdn.firefoxusercontent.com/images/3102aa92-a984-4d02-80f3-0f0e82a46760.jpg)

After
![](https://screenshotscdn.firefoxusercontent.com/images/e7dd4e04-314c-41ad-a994-e37fa6c8370b.jpg)

**Comment by JonasASchmidt** [comment]
I like the proporsal, but do not agree with text-align: justify; this usually leads to worse readability.

**Comment by JonasASchmidt** [comment]
Achieved the limited content width already by padding though.
