### ISSUE TITLE
Make header transparent but logo not

### ISSUE THREAD

**Issue by HerrBertling** [jsunconf/2018.jsunconf.eu#8]
Currently, the JSUnconf logo is transparent since the whole header has its `opacity` set to `0.75`. This means that the logo is transparent as well. I figured this should probably not be the case, so one (me :wink:) could refactor the code to make the gradient use rgba colors to make it transparent and remove the then unneeded opacity to make the logo solid.

I'll give it a try and open a PR soonish. Feel free to merge :)

**Comment by klyrr** [comment]
Thank you so much!
